/*
    Generated by Atomist on 05 07 2016 
*/
package vehicleIdValidation;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class VehicleIdValidationApplication {

    public static void main(String[] args) {
        SpringApplication.run(VehicleIdValidationApplication.class, args);
    }
}
