/*
    Generated by Atomist on 05 07 2016 
*/
package vehicleIdValidation;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = VehicleIdValidationApplication.class)
@WebAppConfiguration
public class VehicleIdValidationApplicationTests {

	@Test
	public void contextLoads() {
	}
}
